apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - configmaps.yaml
  - camera-params.yaml
  - mediamtx.yaml
  - producer.yaml
  - rtsp-streamer.yaml
  - viewer.yaml
