#!/bin/bash
#
# manage_cpusets.sh — cgroup v2 cpuset partition manager.
#
# Creates isolated cpuset partitions for real-time workloads, with support
# for multiple concurrent partitions, batch config files, runtime task
# placement, boot persistence, and optional integration with the EtherCAT
# NIC/IRQ setup provided by setup_ethercat_interface.sh.
#
# Usage:
#   manage_cpusets.sh create <name> <cpus> [--with-ethercat-rt] [--nic <iface>]
#   manage_cpusets.sh remove <name>
#   manage_cpusets.sh list
#   manage_cpusets.sh status
#   manage_cpusets.sh run <name> -- <cmd...>
#   manage_cpusets.sh apply <config-file> [--yes]
#   manage_cpusets.sh verify [<name>]
#   manage_cpusets.sh ethercat-rt <name> [--nic <iface>] [--rt-core <N>]
#   manage_cpusets.sh install-service [<config-file>]
#   manage_cpusets.sh uninstall-service
#   manage_cpusets.sh install-affinity-defaults
#   manage_cpusets.sh uninstall-affinity-defaults
#   manage_cpusets.sh migrate-cmdline [--add-rt-flags]
#   manage_cpusets.sh help
#
# Typical boot ordering: the cpusets.service installed by `install-service`
# runs before docker.service, user@.service, and systemd-logind.service so
# no cgroup has claimed the isolated CPUs before the partition is set up.

set -u  # unbound-var errors; we deliberately do NOT use -e here because
        # subcommands do their own error handling with explicit die().

# ---------- Script locations -----------------------------------------------
# Resolve symlinks so an installed entrypoint like /usr/sbin/dma-ethercat-cpusets
# (symlinked into /usr/lib/dma-ethercat/cpusets/) still finds lib/ adjacent.
_REAL_SOURCE="$(readlink -f "${BASH_SOURCE[0]}" 2>/dev/null || echo "${BASH_SOURCE[0]}")"
SCRIPT_DIR="$(cd "$(dirname "$_REAL_SOURCE")" && pwd)"
LIB_DIR="$SCRIPT_DIR/lib"

# ---------- Colors ---------------------------------------------------------
RED=$'\033[0;31m'
GREEN=$'\033[0;32m'
YELLOW=$'\033[1;33m'
BLUE=$'\033[0;34m'
NC=$'\033[0m'

# ---------- Paths ----------------------------------------------------------
CGROUP_ROOT="/sys/fs/cgroup"
STATE_DIR="/var/lib/manage_cpusets"
STATE_FILE="$STATE_DIR/state"
AFFINITY_DROPIN="/etc/systemd/system.conf.d/cpuaffinity.conf"
CPUSETS_CONF="/etc/cpusets.conf"
CPUSETS_SERVICE="/etc/systemd/system/cpusets.service"
INSTALL_DIR="/usr/local/lib/manage_cpusets"
APPLY_WRAPPER="/usr/local/sbin/apply-cpusets"

# Slices whose cpuset.cpus must be shrunk before an isolated partition can
# activate. Any slice not in this list that still claims one of the target
# CPUs will cause the partition to go "isolated invalid".
#
# Phantom-OS local addition: `kubepods` and `kubepods.slice` cover the
# kubelet root cgroup. k0s/kubelet creates one of these (path varies by
# cgroup driver — `kubepods` for cgroupfs, `kubepods.slice` for
# systemd) at startup covering all CPUs, blocking partition activation.
# We list both so either layout is shrunk safely; the directory check
# in shrink_sibling_slices() makes a missing entry a no-op.
MANAGED_SLICES=(system.slice user.slice init.scope docker.slice kubepods kubepods.slice)

# Minimum number of CPUs to keep un-isolated (safety floor).
HOUSEKEEPING_FLOOR=2

# ---------- Default partition layout ---------------------------------------
# Used when 'install-service' or 'apply' is invoked without a config-file
# argument. Override by passing an explicit INI file.
DEFAULT_PARTITION_NAME="rt"
DEFAULT_PARTITION_CPUS="11-13"

emit_default_config() {
    cat <<EOF
# Default cpuset partition layout for DMA.ethercat.
# Generated by manage_cpusets.sh — edit /etc/cpusets.conf to customize.
#
# Format (INI):
#   [name]
#   cpus = <range>          # e.g. 11-13 or 10,12,14
#   description = <text>    # informational

[${DEFAULT_PARTITION_NAME}]
cpus = ${DEFAULT_PARTITION_CPUS}
description = EtherCAT RT partition (default)
EOF
}

# ---------- Sudo -----------------------------------------------------------
if [[ $EUID -eq 0 ]]; then
    SUDO=""
else
    SUDO="sudo"
fi

# ---------- Source libraries ----------------------------------------------
if [[ ! -d "$LIB_DIR" ]]; then
    echo "ERROR: library directory not found: $LIB_DIR" >&2
    exit 1
fi
# shellcheck source=./lib/cpu_utils.sh
source "$LIB_DIR/cpu_utils.sh"
# shellcheck source=./lib/systemd_units.sh
source "$LIB_DIR/systemd_units.sh"
# nic_rt.sh is only sourced on demand (ethercat-rt subcommand) because it
# pulls in udev helpers that aren't needed for pure cpuset ops.

# ---------- Logging helpers -----------------------------------------------
info()    { echo -e "${BLUE}$*${NC}"; }
warn()    { echo -e "${YELLOW}$*${NC}" >&2; }
success() { echo -e "${GREEN}$*${NC}"; }
error()   { echo -e "${RED}$*${NC}" >&2; }
die()     { error "$*"; exit 1; }

# ---------- Preflights -----------------------------------------------------
require_root() {
    if [[ $EUID -ne 0 && -z "$(command -v sudo)" ]]; then
        die "This operation requires root and 'sudo' is not available."
    fi
}

preflight_cgroup_v2() {
    # Detect via the kernel's own marker file rather than parsing
    # `mount` output — the latter varies between busybox / util-linux /
    # Jetson and was producing false negatives on Phantom-OS hosts.
    if [[ ! -f "$CGROUP_ROOT/cgroup.controllers" ]]; then
        die "cgroup v2 is not mounted at $CGROUP_ROOT. This tool requires cgroup v2."
    fi

    local controllers
    if ! controllers=$(cat "$CGROUP_ROOT/cgroup.controllers" 2>/dev/null); then
        die "Cannot read $CGROUP_ROOT/cgroup.controllers — cgroup v2 not functional."
    fi

    if ! echo "$controllers" | grep -qw cpuset; then
        die "cpuset controller not available. Kernel lacks CONFIG_CPUSETS."
    fi

    # Enable the cpuset controller in subtree_control if it's not already.
    local subtree
    subtree=$(cat "$CGROUP_ROOT/cgroup.subtree_control" 2>/dev/null || echo "")
    if ! echo "$subtree" | grep -qw cpuset; then
        info "Enabling cpuset controller in root subtree_control..."
        echo "+cpuset" | $SUDO tee "$CGROUP_ROOT/cgroup.subtree_control" > /dev/null \
            || die "Failed to enable cpuset controller in subtree_control."
    fi
}

# Warn (interactively) when isolcpus= is present on the kernel cmdline and
# overlaps with the requested partition CPUs.
# Arguments: requested_cpu_list
# Respects --yes flag via global SKIP_PROMPTS=1 (set by `apply --yes` etc.).
check_isolcpus_cmdline() {
    local requested="$1"
    local cmdline_isolcpus overlap stray
    cmdline_isolcpus=$(parse_isolcpus_cmdline)

    [[ -z "$cmdline_isolcpus" ]] && return 0

    # Union of requested + all already-managed partitions.
    local all_managed
    all_managed=$(compute_all_managed_cpus)
    local combined
    combined=$(cpu_list_union "$requested" "$all_managed")

    overlap=$(cpu_list_intersect "$cmdline_isolcpus" "$combined")
    stray=$(cpu_list_diff "$cmdline_isolcpus" "$combined")

    echo ""
    warn "isolcpus= is active on the kernel cmdline: $cmdline_isolcpus"
    if [[ -n "$overlap" ]]; then
        warn "  overlap with managed partitions: $overlap"
        warn "  This is redundant — cpuset partitions cannot dynamically release these cores."
    fi
    if [[ -n "$stray" ]]; then
        warn "  isolated outside any managed partition: $stray"
    fi

    if [[ "${SKIP_PROMPTS:-0}" == "1" ]]; then
        warn "Proceeding (non-interactive mode)."
        return 0
    fi

    echo ""
    echo "Options:"
    echo "  [1] Continue anyway (cpuset partitions layer on top of isolcpus=)"
    echo "  [2] Abort — remove isolcpus= with 'manage_cpusets.sh migrate-cmdline'"
    echo "  [3] Abort — let me pick different CPUs for the partition"
    echo ""
    read -p "Choice [1/2/3]: " -n 1 -r choice
    echo
    case "$choice" in
        1) return 0 ;;
        2) info "Run: $0 migrate-cmdline"; exit 1 ;;
        3) exit 1 ;;
        *) die "Invalid choice." ;;
    esac
}

# ---------- State file -----------------------------------------------------
# Simple line-oriented format: <name>|<cpus>|<epoch_created>
state_init() {
    if [[ ! -d "$STATE_DIR" ]]; then
        $SUDO mkdir -p "$STATE_DIR" || die "Failed to create $STATE_DIR"
    fi
    if [[ ! -f "$STATE_FILE" ]]; then
        $SUDO touch "$STATE_FILE"
    fi
}

state_list_names() {
    state_init
    awk -F'|' 'NF>=2 && $1 != "" {print $1}' "$STATE_FILE"
}

state_get_cpus() {
    local name="$1"
    state_init
    awk -F'|' -v name="$name" 'NF>=2 && $1 == name {print $2; exit}' "$STATE_FILE"
}

state_add() {
    local name="$1" cpus="$2"
    state_init
    state_remove "$name"  # idempotent update
    echo "$name|$cpus|$(date +%s)" | $SUDO tee -a "$STATE_FILE" > /dev/null
}

state_remove() {
    local name="$1"
    state_init
    local tmp
    tmp=$(mktemp)
    awk -F'|' -v name="$name" '$1 != name' "$STATE_FILE" > "$tmp"
    $SUDO cp "$tmp" "$STATE_FILE"
    rm -f "$tmp"
}

# Union of CPUs across every managed partition (from state file).
compute_all_managed_cpus() {
    local combined="" name cpus
    while read -r name; do
        [[ -z "$name" ]] && continue
        cpus=$(state_get_cpus "$name")
        [[ -n "$cpus" ]] && combined=$(cpu_list_union "$combined" "$cpus")
    done < <(state_list_names)
    echo "$combined"
}

# ---------- Partition primitives -------------------------------------------
validate_partition_name() {
    local name="$1"
    [[ "$name" =~ ^[a-zA-Z][a-zA-Z0-9_-]*$ ]] \
        || die "Invalid partition name '$name' (must start with a letter, alphanumeric + _ -)"
    [[ "$name" == "system.slice" || "$name" == "user.slice" || "$name" == "init.scope" ]] \
        && die "Refusing to manage reserved cgroup '$name'"
}

# Validate a requested CPU list: all online, no overlap with other managed
# partitions, housekeeping floor respected.
validate_requested_cpus() {
    local name="$1" cpus="$2"
    local expanded c

    expanded=$(expand_cpu_range "$cpus") \
        || die "Malformed CPU range: $cpus"
    [[ -z "$expanded" ]] && die "Empty CPU range"

    for c in $expanded; do
        cpu_is_online "$c" || die "CPU $c is not online"
    done

    # Overlap with other managed partitions (excluding <name> in case we are
    # updating it).
    local other_name other_cpus overlap
    for other_name in $(state_list_names); do
        [[ "$other_name" == "$name" ]] && continue
        other_cpus=$(state_get_cpus "$other_name")
        overlap=$(cpu_list_intersect "$cpus" "$other_cpus")
        if [[ -n "$overlap" ]]; then
            die "Requested CPUs overlap partition '$other_name' ($other_cpus): $overlap"
        fi
    done

    # Housekeeping floor: count post-create housekeeping cores.
    local present_cpus total_isolated housekeeping_count
    present_cpus=$(get_present_cpus)
    total_isolated=$(cpu_list_union "$(compute_all_managed_cpus)" "$cpus")
    housekeeping_count=$(cpu_list_count "$(cpu_list_diff "$present_cpus" "$total_isolated")")

    if [[ "$housekeeping_count" -lt "$HOUSEKEEPING_FLOOR" ]]; then
        die "Would leave $housekeeping_count housekeeping cores (floor: $HOUSEKEEPING_FLOOR). Refusing."
    fi
}

# Shrink the MANAGED_SLICES to a given cpu range. Idempotent.
shrink_sibling_slices() {
    local housekeeping="$1"
    local slice slice_path cpus_file
    for slice in "${MANAGED_SLICES[@]}"; do
        slice_path="$CGROUP_ROOT/$slice"
        cpus_file="$slice_path/cpuset.cpus"
        [[ ! -d "$slice_path" ]] && continue
        [[ ! -f "$cpus_file" ]] && continue

        local current
        current=$(cat "$cpus_file" 2>/dev/null || echo "")
        # Writing the same value again is cheap; always write to stay consistent.
        if ! echo "$housekeeping" | $SUDO tee "$cpus_file" > /dev/null 2>&1; then
            warn "  Could not shrink $slice/cpuset.cpus (was: '$current')"
        fi
    done
}

# When removing a partition, restore MANAGED_SLICES to cover housekeeping +
# the un-managed cores. Safest default: write the fresh housekeeping range.
restore_sibling_slices() {
    local new_housekeeping
    new_housekeeping=$(cpu_list_diff "$(get_present_cpus)" "$(compute_all_managed_cpus)")
    shrink_sibling_slices "$new_housekeeping"
}

# Identify which other cgroup is still claiming one of the requested CPUs.
# Called when partition activation fails with "isolated invalid".
explain_partition_failure() {
    local name="$1" cpus="$2"
    local partition_file="$CGROUP_ROOT/$name/cpuset.cpus.partition"
    local reason
    reason=$(cat "$partition_file" 2>/dev/null || echo "(unavailable)")
    error "Partition $name did not activate: $reason"

    echo ""
    echo "Searching for sibling cgroups that still claim these CPUs..."
    local dir other_cpus overlap_any=0
    for dir in "$CGROUP_ROOT"/*/; do
        [[ ! -f "$dir/cpuset.cpus" ]] && continue
        local sibling
        sibling=$(basename "$dir")
        [[ "$sibling" == "$name" ]] && continue
        other_cpus=$(cat "$dir/cpuset.cpus" 2>/dev/null || echo "")
        [[ -z "$other_cpus" ]] && continue
        local overlap
        overlap=$(cpu_list_intersect "$cpus" "$other_cpus")
        if [[ -n "$overlap" ]]; then
            warn "  $sibling claims $other_cpus (overlap: $overlap)"
            overlap_any=1
        fi
    done
    [[ $overlap_any -eq 0 ]] && info "  No overlap found. Common alternate causes: partition CPU is offline, or subtree_control missing cpuset."
}

# Create a partition at $CGROUP_ROOT/<name>. Assumes validation done.
activate_partition() {
    local name="$1" cpus="$2"
    local path="$CGROUP_ROOT/$name"

    # Recompute housekeeping including this new partition.
    local new_total new_housekeeping
    new_total=$(cpu_list_union "$(compute_all_managed_cpus)" "$cpus")
    new_housekeeping=$(cpu_list_diff "$(get_present_cpus)" "$new_total")

    info "Shrinking sibling slices to $new_housekeeping..."
    shrink_sibling_slices "$new_housekeeping"

    info "Creating cgroup $path..."
    $SUDO mkdir -p "$path" || die "mkdir $path failed"

    info "Assigning CPUs $cpus..."
    if ! echo "$cpus" | $SUDO tee "$path/cpuset.cpus" > /dev/null; then
        $SUDO rmdir "$path" 2>/dev/null || true
        die "Failed to write cpuset.cpus"
    fi

    info "Activating isolated partition..."
    if ! echo isolated | $SUDO tee "$path/cpuset.cpus.partition" > /dev/null; then
        explain_partition_failure "$name" "$cpus"
        $SUDO rmdir "$path" 2>/dev/null || true
        die "Partition activation failed"
    fi

    local partition_state
    partition_state=$(cat "$path/cpuset.cpus.partition")
    if [[ "$partition_state" != "isolated" ]]; then
        explain_partition_failure "$name" "$cpus"
        $SUDO rmdir "$path" 2>/dev/null || true
        die "Partition state: $partition_state"
    fi

    state_add "$name" "$cpus"
    success "Partition '$name' active on CPUs $cpus"
}

deactivate_partition() {
    local name="$1"
    local path="$CGROUP_ROOT/$name"

    if [[ ! -d "$path" ]]; then
        warn "cgroup $path does not exist — removing from state only"
        state_remove "$name"
        return 0
    fi

    # Move any remaining tasks out (they go to root).
    if [[ -f "$path/cgroup.procs" ]]; then
        local procs
        procs=$(cat "$path/cgroup.procs" 2>/dev/null || true)
        if [[ -n "$procs" ]]; then
            warn "Moving $(echo "$procs" | wc -l | xargs) task(s) out of partition to root"
            while read -r pid; do
                [[ -z "$pid" ]] && continue
                echo "$pid" | $SUDO tee "$CGROUP_ROOT/cgroup.procs" > /dev/null 2>&1 || true
            done <<< "$procs"
        fi
    fi

    # Step down from isolated to member before removing.
    if [[ -f "$path/cpuset.cpus.partition" ]]; then
        echo member | $SUDO tee "$path/cpuset.cpus.partition" > /dev/null 2>&1 || true
    fi

    if ! $SUDO rmdir "$path" 2>/dev/null; then
        warn "rmdir $path failed (busy?)"
    else
        success "Removed cgroup $path"
    fi

    state_remove "$name"
    restore_sibling_slices
}

# ---------- Subcommand: create --------------------------------------------
cmd_create() {
    local name="" cpus="" with_ethercat=0 nic=""
    while [[ $# -gt 0 ]]; do
        case "$1" in
            --with-ethercat-rt) with_ethercat=1; shift ;;
            --nic) nic="$2"; shift 2 ;;
            --yes) SKIP_PROMPTS=1; shift ;;
            -h|--help)
                echo "Usage: $0 create <name> <cpus> [--with-ethercat-rt] [--nic <iface>] [--yes]"
                return 0 ;;
            -*) die "Unknown flag: $1" ;;
            *)
                if [[ -z "$name" ]]; then name="$1"
                elif [[ -z "$cpus" ]]; then cpus="$1"
                else die "Unexpected positional argument: $1"
                fi
                shift ;;
        esac
    done

    [[ -z "$name" || -z "$cpus" ]] && die "Usage: create <name> <cpus> [options]"

    require_root
    preflight_cgroup_v2
    validate_partition_name "$name"
    validate_requested_cpus "$name" "$cpus"
    check_isolcpus_cmdline "$cpus"

    # If updating an existing partition, deactivate first.
    if state_get_cpus "$name" > /dev/null && [[ -n "$(state_get_cpus "$name")" ]]; then
        warn "Partition '$name' exists. Recreating."
        deactivate_partition "$name"
    fi

    activate_partition "$name" "$cpus"

    if [[ $with_ethercat -eq 1 ]]; then
        info ""
        info "Chaining into ethercat-rt setup..."
        cmd_ethercat_rt "$name" ${nic:+--nic "$nic"}
    fi
}

# ---------- Subcommand: remove --------------------------------------------
cmd_remove() {
    local name="${1:-}"
    [[ -z "$name" ]] && die "Usage: remove <name>"

    require_root
    preflight_cgroup_v2
    validate_partition_name "$name"

    local cpus
    cpus=$(state_get_cpus "$name")
    if [[ -z "$cpus" ]]; then
        warn "Partition '$name' not found in state. Attempting cgroup cleanup anyway."
    else
        info "Removing partition '$name' (cpus $cpus)..."
    fi

    deactivate_partition "$name"
}

# ---------- Subcommand: list -----------------------------------------------
cmd_list() {
    local names
    names=$(state_list_names)
    if [[ -z "$names" ]]; then
        echo "No managed partitions."
        return 0
    fi

    printf "%-20s %-15s %-15s %s\n" NAME CPUS STATE CGROUP_PATH
    printf "%-20s %-15s %-15s %s\n" ---- ---- ----- -----------
    local name cpus state
    while read -r name; do
        [[ -z "$name" ]] && continue
        cpus=$(state_get_cpus "$name")
        if [[ -f "$CGROUP_ROOT/$name/cpuset.cpus.partition" ]]; then
            state=$(cat "$CGROUP_ROOT/$name/cpuset.cpus.partition" 2>/dev/null || echo ?)
        else
            state="MISSING"
        fi
        printf "%-20s %-15s %-15s %s\n" "$name" "$cpus" "$state" "$CGROUP_ROOT/$name"
    done <<< "$names"
}

# ---------- Subcommand: status --------------------------------------------
cmd_status() {
    echo "System isolation state"
    echo "----------------------"
    echo "Present CPUs:    $(get_present_cpus)"
    echo "Online CPUs:     $(get_online_cpus)"
    echo "Isolated (sysfs): $(detect_isolated_cores)"
    echo "isolcpus= (cmdline): $(parse_isolcpus_cmdline)"
    echo "nohz_full=         : $(parse_nohz_full_cmdline)"
    echo "rcu_nocbs=         : $(parse_rcu_nocbs_cmdline)"
    echo "irqaffinity=       : $(parse_irqaffinity_cmdline)"
    echo "Housekeeping CPUs: $(compute_housekeeping_list)"
    echo ""
    echo "Managed partitions:"
    cmd_list
    echo ""
    echo "systemd affinity drop-in:"
    if [[ -f "$AFFINITY_DROPIN" ]]; then
        grep -E '^(CPUAffinity|\[Manager\])' "$AFFINITY_DROPIN" | sed 's/^/  /'
    else
        echo "  (not installed)"
    fi
    echo ""
    echo "cpusets.service:"
    if [[ -f "$CPUSETS_SERVICE" ]]; then
        local svc_state
        svc_state=$(systemctl is-enabled cpusets.service 2>/dev/null || echo "?")
        echo "  enabled: $svc_state"
    else
        echo "  (not installed)"
    fi
}

# ---------- Subcommand: run -----------------------------------------------
cmd_run() {
    local name=""
    while [[ $# -gt 0 ]]; do
        case "$1" in
            --) shift; break ;;
            -*) die "Unknown flag: $1" ;;
            *)
                if [[ -z "$name" ]]; then name="$1"; shift
                else break
                fi ;;
        esac
    done

    [[ -z "$name" ]] && die "Usage: run <name> -- <cmd...>"
    [[ $# -eq 0 ]] && die "No command after '--'"

    require_root

    local path="$CGROUP_ROOT/$name"
    [[ -d "$path" ]] || die "Partition '$name' does not exist at $path"

    # Exec into the partition: write our shell pid to cgroup.procs, then exec.
    # Using $SUDO bash -c lets us satisfy the write even when run as non-root.
    info "Executing '$*' inside cpuset '$name'..."
    $SUDO bash -c "echo \$\$ > '$path/cgroup.procs'; exec \"\$@\"" -- "$@"
}

# ---------- Subcommand: apply (INI config) --------------------------------
# Config format:
#   [name]
#   cpus = 10-11
#   description = EtherCAT master
cmd_apply() {
    local config=""
    while [[ $# -gt 0 ]]; do
        case "$1" in
            --yes) SKIP_PROMPTS=1; shift ;;
            -*) die "Unknown flag: $1" ;;
            *)
                [[ -z "$config" ]] && { config="$1"; shift; continue; }
                die "Unexpected argument: $1"
                ;;
        esac
    done

    [[ -z "$config" ]] && die "Usage: apply <config-file> [--yes]"
    [[ -f "$config" ]] || die "Config file not found: $config"

    require_root
    preflight_cgroup_v2

    # Two-pass: parse + validate all sections, then create.
    declare -a names
    declare -A cpus_by_name
    local section="" key="" val="" line
    while IFS= read -r line || [[ -n "$line" ]]; do
        # Strip comments, trim.
        line="${line%%#*}"
        line="$(echo "$line" | xargs)"
        [[ -z "$line" ]] && continue

        if [[ "$line" =~ ^\[(.+)\]$ ]]; then
            section="${BASH_REMATCH[1]}"
            validate_partition_name "$section"
            names+=("$section")
            continue
        fi
        if [[ -z "$section" ]]; then
            die "Config line before any section: $line"
        fi
        if [[ "$line" =~ ^([a-zA-Z_]+)[[:space:]]*=[[:space:]]*(.*)$ ]]; then
            key="${BASH_REMATCH[1]}"
            val="${BASH_REMATCH[2]}"
            case "$key" in
                cpus)        cpus_by_name[$section]="$val" ;;
                description) : ;;  # currently informational
                *)           warn "Ignoring unknown config key '$key' in [$section]" ;;
            esac
        fi
    done < "$config"

    [[ ${#names[@]} -eq 0 ]] && die "No sections in $config"

    # Validation pass (no mutation).
    local n
    for n in "${names[@]}"; do
        local cpus="${cpus_by_name[$n]:-}"
        [[ -z "$cpus" ]] && die "[$n]: cpus = <range> is required"
    done

    # Create pass.
    local created=()
    trap '
        for c in "${created[@]}"; do
            warn "Rolling back partition $c"
            deactivate_partition "$c" || true
        done
    ' ERR

    for n in "${names[@]}"; do
        local cpus="${cpus_by_name[$n]}"
        # If it already exists with same cpus, skip (idempotent).
        local current
        current=$(state_get_cpus "$n")
        if [[ "$current" == "$cpus" && -d "$CGROUP_ROOT/$n" ]]; then
            info "[$n] already active on $cpus — skipping"
            continue
        fi

        validate_requested_cpus "$n" "$cpus"
        # Per-partition isolcpus check.
        check_isolcpus_cmdline "$cpus"

        if [[ -n "$current" ]]; then
            deactivate_partition "$n"
        fi
        activate_partition "$n" "$cpus"
        created+=("$n")
    done

    trap - ERR
    success "Applied $(echo "${names[@]}" | wc -w) partition(s)."
}

# ---------- Subcommand: ethercat-rt ---------------------------------------
cmd_ethercat_rt() {
    local name="" nic="" rt_core=""
    while [[ $# -gt 0 ]]; do
        case "$1" in
            --nic) nic="$2"; shift 2 ;;
            --rt-core) rt_core="$2"; shift 2 ;;
            -*) die "Unknown flag: $1" ;;
            *)
                [[ -z "$name" ]] && { name="$1"; shift; continue; }
                die "Unexpected argument: $1"
                ;;
        esac
    done

    [[ -z "$name" ]] && \
        die "Usage: ethercat-rt <partition> [--nic <iface>] [--rt-core <N>]"

    require_root

    local cpus
    cpus=$(state_get_cpus "$name")
    [[ -z "$cpus" ]] && die "Partition '$name' not found"

    # Lazy-source nic_rt.sh (not needed for pure cpuset ops).
    # shellcheck source=./lib/nic_rt.sh
    source "$LIB_DIR/nic_rt.sh"

    # Offer the partition's cpus as the RT candidate set.
    export RT_CANDIDATE_CORES="$cpus"
    nic="${nic:-ecat0}"

    if ! ip link show "$nic" &>/dev/null; then
        die "Interface $nic not found. Run setup_ethercat_interface.sh to create it first."
    fi

    info "Running EtherCAT RT setup for partition '$name' on $nic..."
    if [[ -n "$rt_core" ]]; then
        # Non-interactive path used by Phantom-OS-KubernetesOptions
        # bootstrap (FIR-269). Validate the operator-supplied core lies
        # inside the partition before short-circuiting select_rt_core.
        # cpu_utils.sh already provides cpu_list_contains.
        if ! cpu_list_contains "$cpus" "$rt_core"; then
            die "--rt-core $rt_core is not in partition '$name' cpus ($cpus)"
        fi
        export RT_CORE="$rt_core"
        info "RT core selected non-interactively: $RT_CORE"
    else
        if ! select_rt_core; then
            die "Core selection aborted"
        fi
    fi

    local irqs
    irqs=$(find_nic_irqs "$nic")
    [[ -z "$irqs" ]] && die "No IRQs found for $nic"

    info "IRQs: $irqs"
    # shellcheck disable=SC2086
    pin_irqs_to_core "$RT_CORE" $irqs
    # shellcheck disable=SC2086
    configure_irqbalance $irqs
    write_ethercat_rt_service "$nic" "$RT_CORE"
    apply_nic_tuning "$nic"
    create_nic_tuning_dispatcher "$nic"
    lock_isolated_core_governors
    restrict_workqueue_mask
    check_kernel_params "$RT_CORE"

    success "ethercat-rt complete on partition '$name' core $RT_CORE"
}

# ---------- Subcommand: verify --------------------------------------------
cmd_verify() {
    local name="${1:-}"
    local fail=0

    echo "Verification"
    echo "------------"

    # Phase 0: preconditions
    echo "[Phase 0] Preconditions"
    if [[ -f "$CGROUP_ROOT/cgroup.controllers" ]]; then
        success "  cgroup v2 mounted"
    else
        error "  cgroup v2 NOT mounted"; fail=1
    fi
    if grep -qw cpuset "$CGROUP_ROOT/cgroup.controllers" 2>/dev/null; then
        success "  cpuset controller available"
    else
        error "  cpuset controller NOT available"; fail=1
    fi
    if grep -qw cpuset "$CGROUP_ROOT/cgroup.subtree_control" 2>/dev/null; then
        success "  cpuset in subtree_control"
    else
        warn "  cpuset not in subtree_control (will be enabled on create)"
    fi

    # Phase 1/2: partition lifecycle + integrity
    echo ""
    echo "[Phase 1/2] Partition state"
    local names
    if [[ -n "$name" ]]; then
        names="$name"
    else
        names=$(state_list_names)
    fi
    if [[ -z "$names" ]]; then
        info "  No managed partitions."
    else
        local n cpus state effective path
        for n in $names; do
            path="$CGROUP_ROOT/$n"
            cpus=$(state_get_cpus "$n")
            if [[ ! -d "$path" ]]; then
                error "  $n: cgroup $path missing"; fail=1; continue
            fi
            state=$(cat "$path/cpuset.cpus.partition" 2>/dev/null || echo ?)
            effective=$(cat "$path/cpuset.cpus.effective" 2>/dev/null || echo ?)
            if [[ "$state" != "isolated" ]]; then
                error "  $n: partition state '$state' (expected 'isolated')"; fail=1
            else
                success "  $n: partition isolated on $effective"
            fi
            if [[ "$effective" != "$cpus" ]]; then
                warn "  $n: effective cpus $effective differs from requested $cpus"
            fi
            # Verify sibling slices don't claim these CPUs.
            local slice
            for slice in "${MANAGED_SLICES[@]}"; do
                local slice_path="$CGROUP_ROOT/$slice"
                [[ ! -f "$slice_path/cpuset.cpus.effective" ]] && continue
                local sib_eff overlap
                sib_eff=$(cat "$slice_path/cpuset.cpus.effective" 2>/dev/null || echo "")
                overlap=$(cpu_list_intersect "$cpus" "$sib_eff")
                if [[ -n "$overlap" ]]; then
                    error "  $n: $slice still claims $overlap"; fail=1
                fi
            done
        done
    fi

    # Phase 3: task placement
    echo ""
    echo "[Phase 3] Task placement"
    local isolated
    isolated=$(detect_isolated_cores)
    if [[ -z "$isolated" ]]; then
        warn "  No cores isolated — cannot check placement"
    else
        local isolated_list
        isolated_list=$(expand_cpu_range "$isolated")
        # Sample: check for user-space procs running on isolated cores.
        local stray
        stray=$(ps -eo psr,pid,comm,cgroup 2>/dev/null \
                  | awk -v cores="$isolated_list" 'BEGIN{split(cores,a," "); for(i in a) ci[a[i]]=1} NR>1 && ($1 in ci) && $3 !~ /^(migration|ksoftirqd|cpuhp|idle_inject|rcu|kworker)/' \
                  | head -5)
        if [[ -n "$stray" ]]; then
            warn "  Tasks on isolated cores (may be legitimate RT workload):"
            echo "$stray" | sed 's/^/    /'
        else
            success "  No unexpected tasks on isolated cores"
        fi
    fi

    # Phase 3.5: affinity drop-in effect
    echo ""
    echo "[Phase 3.5] systemd default CPUAffinity"
    if [[ -f "$AFFINITY_DROPIN" ]]; then
        local installed_affinity
        installed_affinity=$(grep -E '^CPUAffinity=' "$AFFINITY_DROPIN" | cut -d= -f2)
        success "  $AFFINITY_DROPIN present: CPUAffinity=$installed_affinity"
        local expected
        expected=$(compute_housekeeping_list)
        if [[ "$installed_affinity" != "$expected" ]]; then
            warn "  Drop-in value differs from current housekeeping ($expected)"
        fi
    else
        warn "  $AFFINITY_DROPIN not installed (optional — install-affinity-defaults)"
    fi

    echo ""
    if [[ $fail -eq 0 ]]; then
        success "All checks passed."
    else
        error "Some checks failed."
        return 1
    fi
}

# ---------- Subcommand: install-affinity-defaults -------------------------
cmd_install_affinity_defaults() {
    require_root
    local housekeeping
    housekeeping=$(compute_housekeeping_list)
    [[ -z "$housekeeping" ]] && die "No housekeeping cores resolved — refusing to write empty CPUAffinity"
    write_affinity_drop_in "$housekeeping" "$AFFINITY_DROPIN"
}

cmd_uninstall_affinity_defaults() {
    require_root
    remove_affinity_drop_in "$AFFINITY_DROPIN"
}

# ---------- Subcommand: install-service -----------------------------------
cmd_install_service() {
    local config="${1:-}"

    require_root

    if [[ -z "$config" ]]; then
        # No config given: synthesize the built-in default into a tempfile
        # and let write_cpusets_service copy it to $CPUSETS_CONF as usual.
        config=$(mktemp)
        # shellcheck disable=SC2064
        trap "rm -f '$config'" RETURN
        emit_default_config > "$config"
        info "No config file given — using built-in default ([${DEFAULT_PARTITION_NAME}] cpus=${DEFAULT_PARTITION_CPUS})."
    else
        [[ -f "$config" ]] || die "Config file not found: $config"
    fi

    write_cpusets_service "$SCRIPT_DIR/manage_cpusets.sh" "$config" \
        "$INSTALL_DIR" "$APPLY_WRAPPER" "$CPUSETS_CONF" "$CPUSETS_SERVICE"

    echo ""
    info "Boot persistence installed. Note:"
    echo "  - Config lives at $CPUSETS_CONF (copy of what you passed)"
    echo "  - Scripts installed to $INSTALL_DIR"
    echo "  - Service: systemctl {start,stop,status} $(basename "$CPUSETS_SERVICE")"
    echo ""
    warn "systemd CPUAffinity drop-in was NOT installed (run 'install-affinity-defaults' if you want it)."
}

cmd_uninstall_service() {
    require_root
    remove_cpusets_service "$INSTALL_DIR" "$APPLY_WRAPPER" "$CPUSETS_CONF" "$CPUSETS_SERVICE"
}

# Internal: called by cpusets.service ExecStop to tear down partitions.
cmd_uninstall_runtime() {
    require_root
    local n
    for n in $(state_list_names); do
        [[ -z "$n" ]] && continue
        deactivate_partition "$n"
    done
}

# ---------- Subcommand: migrate-cmdline -----------------------------------
# Detects the bootloader, removes isolcpus=* from the cmdline, optionally
# adds rt flags, shows a diff, and applies atomically after confirmation.
cmd_migrate_cmdline() {
    local add_rt_flags=0
    while [[ $# -gt 0 ]]; do
        case "$1" in
            --add-rt-flags) add_rt_flags=1; shift ;;
            --yes) SKIP_PROMPTS=1; shift ;;
            -*) die "Unknown flag: $1" ;;
            *)  die "Unexpected argument: $1" ;;
        esac
    done

    require_root

    local bootloader="" config_file="" current=""
    if [[ -f "/boot/extlinux/extlinux.conf" ]]; then
        bootloader="extlinux"
        config_file="/boot/extlinux/extlinux.conf"
    elif [[ -f "/etc/default/grub" ]]; then
        bootloader="grub"
        config_file="/etc/default/grub"
    else
        die "No supported bootloader config found (/boot/extlinux/extlinux.conf or /etc/default/grub)."
    fi

    info "Detected bootloader: $bootloader ($config_file)"

    # Extract the current APPEND or GRUB_CMDLINE_LINUX_DEFAULT line.
    # On extlinux, scope edits to the DEFAULT label's APPEND only —
    # Jetson's extlinux.conf typically carries multiple LABEL blocks
    # (primary, recovery, …) each with their own APPEND, and we MUST
    # NOT touch the recovery one.
    local line_pattern new_line default_label="" awk_scope=""
    if [[ "$bootloader" == "extlinux" ]]; then
        default_label=$(grep -E '^\s*DEFAULT\s' "$config_file" | head -1 | awk '{print $2}')
        if [[ -n "$default_label" ]]; then
            info "extlinux DEFAULT label: $default_label"
            # Pull APPEND from inside the matching LABEL block.
            current=$(awk -v lbl="$default_label" '
                /^\s*LABEL\s/  { in_block = ($2 == lbl) }
                in_block && /^\s*APPEND\s/ { print; exit }
            ' "$config_file")
            awk_scope="$default_label"
        else
            warn "no DEFAULT label found — falling back to first APPEND line"
            current=$(grep -E '^\s*APPEND\s' "$config_file" | head -1)
        fi
        [[ -z "$current" ]] && die "No APPEND line for label '$default_label' in $config_file"
        # awk uses POSIX EREs and does not honor \s. Use [[:space:]].
        line_pattern='^[[:space:]]*APPEND[[:space:]]'
    else
        current=$(grep -E '^\s*GRUB_CMDLINE_LINUX(_DEFAULT)?=' "$config_file" | head -1)
        [[ -z "$current" ]] && die "No GRUB_CMDLINE_LINUX line in $config_file"
        line_pattern='^[[:space:]]*GRUB_CMDLINE_LINUX(_DEFAULT)?='
    fi

    # Remove isolcpus=<anything> tokens.
    new_line=$(echo "$current" | sed -E 's/\s*isolcpus=[^ "]*//g' | sed -E 's/\s+/ /g')

    if [[ $add_rt_flags -eq 1 ]]; then
        local hk
        hk=$(compute_housekeeping_list)
        local need=("rcu_nocb_poll" "skew_tick=1" "irqaffinity=$hk")
        local flag
        for flag in "${need[@]}"; do
            local key="${flag%%=*}"
            if [[ "$flag" == *"="* ]]; then
                # key=value: strip "key=anything" before re-adding.
                new_line=$(echo "$new_line" | sed -E "s/\s*${key}=[^ \"]*//g" | sed -E 's/\s+/ /g')
            else
                # bare flag: strip the bare token (with word boundaries)
                # so we don't double-add when it's already present and
                # don't accidentally chew through a longer-prefix flag.
                new_line=$(echo "$new_line" | sed -E "s/(^|\s)${key}(\s|$|\")/\1\2/g" | sed -E 's/\s+/ /g')
            fi
            # insert inside the quoted string if present, else append
            if [[ "$new_line" =~ \" ]]; then
                new_line=$(echo "$new_line" | sed -E "s/\"([^\"]*)\"/\"\1 ${flag}\"/")
            else
                new_line="$new_line $flag"
            fi
        done
    fi

    echo ""
    echo "--- current ---"
    echo "$current"
    echo "--- proposed ---"
    echo "$new_line"
    echo "---"

    if [[ "$current" == "$new_line" ]]; then
        info "No change needed."
        return 0
    fi

    # Refuse if the cmdline is ambiguous. extlinux is allowed to have
    # multiple APPEND lines (one per LABEL); we scope the edit to
    # default_label below. GRUB has exactly one GRUB_CMDLINE_LINUX*
    # line by convention — anything else is operator-edited and we
    # refuse rather than risk corrupting it.
    if [[ "$bootloader" == "grub" ]]; then
        if [[ "$(grep -cE "$line_pattern" "$config_file")" -ne 1 ]]; then
            die "Multiple $line_pattern lines in $config_file — refusing to auto-edit. Please edit manually."
        fi
    elif [[ -z "$default_label" ]]; then
        # extlinux without DEFAULT label = ambiguous; fall back to
        # the original strict refusal so we don't blast every label.
        if [[ "$(grep -cE "$line_pattern" "$config_file")" -ne 1 ]]; then
            die "Multiple $line_pattern lines in $config_file and no DEFAULT label — refusing to auto-edit. Please edit manually."
        fi
    fi

    if [[ "${SKIP_PROMPTS:-0}" != "1" ]]; then
        echo ""
        read -p "Apply this change? [y/N] " -n 1 -r
        echo
        [[ ! $REPLY =~ ^[Yy]$ ]] && { info "Aborted."; return 0; }
    fi

    # Backup.
    local backup
    backup="${config_file}.bak.$(date +%Y%m%d-%H%M%S)"
    $SUDO cp "$config_file" "$backup" || die "Backup failed"
    success "Backed up to $backup"

    # Atomic write via tempfile. On extlinux with a DEFAULT label,
    # only replace the APPEND inside that LABEL block — leave other
    # labels (recovery, etc.) untouched. Otherwise replace the first
    # matching line.
    local tmp
    tmp=$(mktemp)
    if [[ "$bootloader" == "extlinux" && -n "$awk_scope" ]]; then
        awk -v pat="$line_pattern" -v repl="$new_line" -v lbl="$awk_scope" '
            /^[[:space:]]*LABEL[[:space:]]/ { in_block = ($2 == lbl) }
            {
                if (in_block && match($0, pat) && !done) { print repl; done=1 }
                else { print }
            }
        ' "$config_file" > "$tmp"
    else
        awk -v pat="$line_pattern" -v repl="$new_line" '
            {
                if (match($0, pat) && !done) { print repl; done=1 }
                else { print }
            }
        ' "$config_file" > "$tmp"
    fi

    $SUDO cp "$tmp" "$config_file.new"
    $SUDO mv "$config_file.new" "$config_file"
    rm -f "$tmp"

    success "Updated $config_file"

    if [[ "$bootloader" == "grub" ]]; then
        info "Running update-grub..."
        $SUDO update-grub
    fi

    echo ""
    warn "Reboot required for the new cmdline to take effect."
}

# ---------- Help -----------------------------------------------------------
cmd_help() {
    local prog
    prog=$(basename "$0")
    cat <<EOF
manage_cpusets.sh — cgroup v2 cpuset partition manager.

Usage:
  $prog <subcommand> [options]

Partition lifecycle:
  create <name> <cpus> [--with-ethercat-rt] [--nic <iface>] [--yes]
      Create a new isolated cpuset partition covering <cpus>. Shrinks
      system.slice / user.slice / init.scope / docker.slice to
      housekeeping cores first so the partition can claim its CPUs
      exclusively. --with-ethercat-rt chains into 'ethercat-rt' after
      activation (and --nic picks the iface, defaults to ecat0).
      --yes skips the isolcpus overlap prompt.
      Example:  sudo $prog create rt 13

  remove <name>
      Deactivate the partition, move any tasks still inside it back to
      the root cgroup, and delete the cgroup directory. Sibling slices
      are re-expanded to cover the newly freed cores.
      Example:  sudo $prog remove rt

Query:
  list
      Table of managed partitions: name, CPUs, current partition state
      (isolated / member / MISSING), and cgroup path.

  status
      Global isolation snapshot: present and online CPUs, isolcpus= /
      nohz_full= / rcu_nocbs= / irqaffinity= from /proc/cmdline, sysfs
      isolated set, computed housekeeping cores, managed partitions,
      systemd affinity drop-in, cpusets.service state.

Execution:
  run <name> -- <cmd...>
      Place the invoking shell into the named partition's cgroup, then
      exec <cmd>. The command inherits the partition's CPU set. Useful
      for ad-hoc testing and one-off pinned runs; for permanent
      services use a systemd unit with AllowedCPUs= instead.
      Example:  sudo $prog run rt -- cyclictest -p 95 -t 1 -a 13

Batch config:
  apply <config-file> [--yes]
      Read an INI config file and reconcile partitions to match it.
      Two-pass: validates every section (names, CPU ranges, overlap,
      housekeeping floor) before mutating anything. Already-correct
      partitions are skipped. On mid-run failure, partitions created
      during this invocation are rolled back. --yes skips interactive
      prompts.
      INI format:
        [ecat]
        cpus = 10-11
        description = EtherCAT master

Verification:
  verify [<name>]
      Run the verification suite. Exits nonzero on any failure.
        Phase 0:   cgroup v2 mounted, cpuset controller present.
        Phase 1/2: partition state = 'isolated', effective CPUs
                   match requested, sibling slices don't claim the
                   partition's CPUs.
        Phase 3:   no unexpected userspace tasks on isolated cores.
        Phase 3.5: systemd affinity drop-in present and matches the
                   current housekeeping set.
      If <name> is omitted, verifies all managed partitions.

EtherCAT integration:
  ethercat-rt <name> [--nic <iface>]
      On an existing partition: pin the NIC's IRQs to one of its
      cores, apply ethtool low-latency tuning (100M/full-duplex, no
      autoneg, coalescing off, offloads off, small rings, napi defer
      on), install the boot-persistence service, lock the performance
      governor on every isolated core, and restrict unbound
      workqueues to housekeeping cores. --nic defaults to ecat0. The
      partition must already exist (use 'create' first, or use
      'create --with-ethercat-rt' to do both in one step).

Boot persistence:
  install-service [<config-file>]
      Install /etc/systemd/system/cpusets.service so partitions
      activate at boot. Copies this script and lib/*.sh to
      /usr/local/lib/manage_cpusets/ so the service is self-contained
      and survives the source tree moving. Service ordering:
      Before=docker.service user@.service systemd-logind.service
      so their cgroups cannot claim the isolated CPUs before the
      partition is active. If <config-file> is omitted, the built-in
      default ([${DEFAULT_PARTITION_NAME}] cpus=${DEFAULT_PARTITION_CPUS})
      is materialized to /etc/cpusets.conf.
      Example:  sudo $prog install-service /etc/cpusets.conf

  uninstall-service
      Disable the service and remove the installed scripts, config
      copy (/etc/cpusets.conf), wrapper
      (/usr/local/sbin/apply-cpusets), and unit file.

systemd default affinity:
  install-affinity-defaults
      Write /etc/systemd/system.conf.d/cpuaffinity.conf with
      [Manager] CPUAffinity=<housekeeping>. This restricts the
      default CPU affinity of every systemd-spawned service to
      non-isolated cores, keeping stray processes off your RT cores.
      Needs 'systemctl daemon-reexec' or a reboot to take effect for
      services started before this edit.

  uninstall-affinity-defaults
      Remove the drop-in. daemon-reexec / reboot to revert.

Kernel cmdline editing:
  migrate-cmdline [--add-rt-flags] [--yes]
      Edit the kernel cmdline to remove isolcpus=*. Detects bootloader
      (Jetson /boot/extlinux/extlinux.conf or GRUB /etc/default/grub),
      makes a timestamped backup, shows the proposed diff, and applies
      atomically after confirmation. --add-rt-flags also injects
      rcu_nocb_poll, skew_tick=1, and irqaffinity=<housekeeping>.
      For GRUB, runs update-grub after. Reboot required for the new
      cmdline to take effect.

Help:
  help, -h, --help
      Show this message.

Examples:
  # Single partition + pinned command:
  sudo $prog create rt 13
  sudo $prog run rt -- ./my_program

  # Multi-partition from config:
  sudo $prog apply /etc/cpusets.conf

  # Full migration from isolcpus= to cpuset partitions:
  sudo $prog install-service /etc/cpusets.conf
  sudo $prog install-affinity-defaults
  sudo $prog migrate-cmdline --add-rt-flags
  sudo reboot
EOF
}

# ---------- Dispatch -------------------------------------------------------
main() {
    local cmd="${1:-help}"
    shift || true

    case "$cmd" in
        create)                        cmd_create "$@" ;;
        remove)                        cmd_remove "$@" ;;
        list)                          cmd_list "$@" ;;
        status)                        cmd_status "$@" ;;
        run)                           cmd_run "$@" ;;
        apply)                         cmd_apply "$@" ;;
        verify)                        cmd_verify "$@" ;;
        ethercat-rt)                   cmd_ethercat_rt "$@" ;;
        install-service)               cmd_install_service "$@" ;;
        uninstall-service)             cmd_uninstall_service "$@" ;;
        uninstall-runtime)             cmd_uninstall_runtime "$@" ;;
        install-affinity-defaults)     cmd_install_affinity_defaults "$@" ;;
        uninstall-affinity-defaults)   cmd_uninstall_affinity_defaults "$@" ;;
        migrate-cmdline)               cmd_migrate_cmdline "$@" ;;
        help|-h|--help)                cmd_help ;;
        *)
            error "Unknown subcommand: $cmd"
            cmd_help
            exit 1
            ;;
    esac
}

main "$@"
