# Generated by tools/phantomos-ops/build.sh — do not edit by hand.
# Embedded at zipapp build time so `phantomos-ops --version` can
# report a stamp without needing git at run time.
BUILD_TAG = "0780e64, dirty"
