apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonAnnotations:
  robot: ak-007
  fleet: phantomos
resources:
- ../../base/runtime-classes
- ../../base/registry
- ../../base/dma-video
- ../../base/positronic
- ../../base/phantomos-api-server
- ../../base/yovariable-server
images:
- name: foundationbot/argus.operator-ui
  newTag: 585e58803318f5366d793986ad3e6129538b8a81
- name: localhost:5443/positronic-control
  newTag: 0.2.46-dev.1-cu130
  newName: foundationbot/phantom-cuda
- name: localhost:5443/phantom-models
  newTag: 2026-04-29
- name: foundationbot/yovariable-server
  newTag: V-1-0-13-20260519-234514-arm64
patches:
- path: patches/positronic-control-imagepullsecrets.yaml
  target:
    kind: Deployment
    name: positronic-control
    namespace: positronic
