#!/usr/bin/env bash
# build.sh — produce a self-contained zipapp of phantomos-ops.
#
# Operators don't need pip on the target host — just python3 (>=3.11)
# and the produced file. Built artefact lands at dist/phantomos-ops
# and is directly executable.
#
# Versioning:
#   The package version comes from src/phantomos_ops/__init__.py
#   (single source of truth — pyproject.toml, the --version CLI flag,
#   and the help-overlay's About tab all read it).
#
#   The built zipapp embeds the version + the build's git SHA so
#   `phantomos-ops --version` reports e.g.
#     phantomos-ops 0.1.0 (a1b2c3d, dirty)
#   making it trivial to identify which build a robot has.
#
# Usage:
#   bash tools/phantomos-ops/build.sh           # builds dist/phantomos-ops
#   bash tools/phantomos-ops/build.sh --clean   # remove dist/ and build/ first

set -euo pipefail

cd "$(dirname "$0")"

if [ "${1:-}" = "--clean" ]; then
  rm -rf dist build *.egg-info src/*.egg-info
fi

# Version + SHA stamp. The SHA stamp lands in src/phantomos_ops/_build.py
# so the runtime can report it without a git dependency at run time.
VERSION="$(grep -E '^__version__' src/phantomos_ops/__init__.py \
            | sed -E 's/.*= *"([^"]+)".*/\1/')"
SHA="$(git rev-parse --short HEAD 2>/dev/null || echo unknown)"
DIRTY=""
if ! git diff --quiet HEAD -- . 2>/dev/null; then
  DIRTY=", dirty"
fi
BUILD_TAG="${SHA}${DIRTY}"

cat > src/phantomos_ops/_build.py <<EOF
# Generated by tools/phantomos-ops/build.sh — do not edit by hand.
# Embedded at zipapp build time so \`phantomos-ops --version\` can
# report a stamp without needing git at run time.
BUILD_TAG = "${BUILD_TAG}"
EOF

# Use the venv's tools where available; fall back to system pip if not.
PIP="${PIP:-pip}"
SHIV="${SHIV:-shiv}"
if [ -x ".venv/bin/pip" ]; then PIP=".venv/bin/pip"; fi
if [ -x ".venv/bin/shiv" ]; then SHIV=".venv/bin/shiv"; fi

mkdir -p dist
echo "Building phantomos-ops $VERSION ($BUILD_TAG) → dist/phantomos-ops"

# shiv bundles the wheel + every runtime dep into a single zipapp.
# -p picks the shebang interpreter on the target host. /usr/bin/env
# python3 keeps it portable across Ubuntu / Jetson where /usr/bin/python3
# is symlinked to whatever the platform default is (3.11 / 3.12).
"$SHIV" \
  --output-file dist/phantomos-ops \
  --entry-point phantomos_ops.__main__:main \
  --python "/usr/bin/env python3" \
  --compressed \
  .

chmod +x dist/phantomos-ops

ls -lh dist/phantomos-ops
echo
echo "Run with:  ./dist/phantomos-ops --version"
echo "         or copy dist/phantomos-ops to the target host."
