#!/bin/bash
# lib/systemd_units.sh — Writers and removers for systemd units used by the
# EtherCAT and cpuset tooling.
#
# Units managed here:
#   - /etc/systemd/system/ethercat-irq-affinity.service   (NIC IRQ + NIC tune)
#   - /etc/systemd/system/cpusets.service                  (cpuset partitions)
#   - /etc/systemd/system.conf.d/cpuaffinity.conf          (default CPUAffinity)
#
# Design note: generated boot scripts are self-contained (no runtime source
# dependencies on this tree) so they survive the source tree being moved or
# deleted. The one exception is the cpusets.service wrapper, which shells
# out to a manage_cpusets.sh at an install path chosen by the caller.

[[ -n "${__SYSTEMD_UNITS_SH_SOURCED:-}" ]] && return 0
__SYSTEMD_UNITS_SH_SOURCED=1

if [[ -z "${BASH_VERSION:-}" ]]; then
    echo "systemd_units.sh requires bash." >&2
    return 1 2>/dev/null || exit 1
fi

_systemd_units_lib_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=./cpu_utils.sh
source "$_systemd_units_lib_dir/cpu_utils.sh"
# shellcheck source=./nic_rt.sh
source "$_systemd_units_lib_dir/nic_rt.sh"

: "${GREEN:=$'\033[0;32m'}"
: "${YELLOW:=$'\033[1;33m'}"
: "${BLUE:=$'\033[0;34m'}"
: "${NC:=$'\033[0m'}"

if [[ -z "${SUDO+x}" ]]; then
    if [[ $EUID -eq 0 ]]; then SUDO=""; else SUDO="sudo"; fi
fi

# ===========================================================================
# EtherCAT IRQ affinity service
# ===========================================================================
#
# Generates a self-contained boot script and systemd unit that at boot:
#   1. Wait for the NIC to appear
#   2. Discover its IRQs
#   3. Pin them to the chosen isolated core
#   4. Apply ethtool NIC tuning
#   5. Lock performance governor on all isolated cores
#   6. Restrict unbound workqueues to housekeeping cores
#
# Arguments: nic, core, [service_path], [script_path]
write_ethercat_rt_service() {
    local nic="$1"
    local core="$2"
    local service_path="${3:-/etc/systemd/system/ethercat-irq-affinity.service}"
    local script_path="${4:-/usr/local/bin/ethercat-irq-affinity.sh}"

    echo -e "${BLUE}Writing EtherCAT RT systemd service...${NC}"

    local nic_tune_snippet
    nic_tune_snippet=$(emit_nic_tuning_snippet "$nic")

    $SUDO tee "$script_path" > /dev/null <<BOOT_EOF
#!/bin/bash
# Auto-generated by manage_cpusets.sh / setup_ethercat_interface.sh
# EtherCAT boot-time RT setup:
#   - Pin NIC IRQs to a single isolated core
#   - Apply ethtool NIC tuning
#   - Lock performance governor on isolated cores
#   - Restrict unbound kernel workqueues to housekeeping cores
#
# Self-contained: does not source any other file in the source tree.

set -u
NIC="$nic"
ISOLATED_CORE=$core
CPU_MASK_HEX=\$(printf "%x" \$((1 << ISOLATED_CORE)))

# --- Wait for the NIC to appear (up to 30s) -------------------------------
for _i in \$(seq 1 30); do
    [[ -d "/sys/class/net/\$NIC" ]] && break
    sleep 1
done

if [[ ! -d "/sys/class/net/\$NIC" ]]; then
    echo "ERROR: \$NIC not found after 30s"
    exit 1
fi

# --- Discover and pin NIC IRQs -------------------------------------------
IRQS=""
[[ -d "/sys/class/net/\$NIC/device/msi_irqs" ]] && IRQS="\$IRQS \$(ls /sys/class/net/\$NIC/device/msi_irqs/ 2>/dev/null)"
[[ -f "/sys/class/net/\$NIC/device/irq" ]]     && IRQS="\$IRQS \$(cat /sys/class/net/\$NIC/device/irq 2>/dev/null)"
IRQS="\$IRQS \$(grep -E "\$NIC" /proc/interrupts 2>/dev/null | awk -F: '{print \$1}' | tr -d ' ')"

PINNED=0
for irq in \$(echo \$IRQS | tr ' ' '\n' | sort -u); do
    [[ -z "\$irq" ]] && continue
    if [[ -f "/proc/irq/\$irq/smp_affinity" ]]; then
        if echo \$CPU_MASK_HEX > /proc/irq/\$irq/smp_affinity 2>/dev/null; then
            PINNED=\$((PINNED + 1))
        fi
    fi
done
echo "Pinned \$PINNED IRQs for \$NIC to core \$ISOLATED_CORE"

# --- Apply ethtool NIC tuning -------------------------------------------
$nic_tune_snippet
echo "NIC tuning applied for \$NIC"

# --- Lock performance governor on all isolated cores --------------------
ISOLATED_LIST=\$(cat /sys/devices/system/cpu/isolated 2>/dev/null || true)
if [[ -n "\$ISOLATED_LIST" ]]; then
    # Expand "10-13,15" into individual cores.
    LOCKED=0
    EXPANDED=""
    REMAINING="\$ISOLATED_LIST"
    while [[ -n "\$REMAINING" ]]; do
        if [[ "\$REMAINING" == *,* ]]; then
            PART="\${REMAINING%%,*}"
            REMAINING="\${REMAINING#*,}"
        else
            PART="\$REMAINING"
            REMAINING=""
        fi
        if [[ "\$PART" == *-* ]]; then
            S="\${PART%-*}"
            E="\${PART#*-}"
            for ((c=S; c<=E; c++)); do EXPANDED="\$EXPANDED \$c"; done
        else
            EXPANDED="\$EXPANDED \$PART"
        fi
    done
    for c in \$EXPANDED; do
        GOV="/sys/devices/system/cpu/cpu\$c/cpufreq/scaling_governor"
        if [[ -w "\$GOV" ]] && echo performance > "\$GOV" 2>/dev/null; then
            LOCKED=\$((LOCKED + 1))
        fi
    done
    echo "Locked performance governor on \$LOCKED isolated cores"
fi

# --- Restrict unbound workqueues to housekeeping cores ------------------
PRESENT=\$(cat /sys/devices/system/cpu/present 2>/dev/null || echo "")
if [[ -n "\$PRESENT" && -n "\$ISOLATED_LIST" ]]; then
    # Compute housekeeping = present - isolated, then hex mask.
    declare -A ISO_SET=()
    for c in \$EXPANDED; do ISO_SET[\$c]=1; done
    PRESENT_REMAINING="\$PRESENT"
    HK_EXPANDED=""
    while [[ -n "\$PRESENT_REMAINING" ]]; do
        if [[ "\$PRESENT_REMAINING" == *,* ]]; then
            PART="\${PRESENT_REMAINING%%,*}"
            PRESENT_REMAINING="\${PRESENT_REMAINING#*,}"
        else
            PART="\$PRESENT_REMAINING"
            PRESENT_REMAINING=""
        fi
        if [[ "\$PART" == *-* ]]; then
            S="\${PART%-*}"
            E="\${PART#*-}"
            for ((c=S; c<=E; c++)); do
                [[ -z "\${ISO_SET[\$c]:-}" ]] && HK_EXPANDED="\$HK_EXPANDED \$c"
            done
        else
            [[ -z "\${ISO_SET[\$PART]:-}" ]] && HK_EXPANDED="\$HK_EXPANDED \$PART"
        fi
    done
    HK_MASK=0
    for c in \$HK_EXPANDED; do HK_MASK=\$((HK_MASK | (1 << c))); done
    if [[ "\$HK_MASK" -gt 0 && -e /sys/devices/virtual/workqueue/cpumask ]]; then
        printf "%x" "\$HK_MASK" > /sys/devices/virtual/workqueue/cpumask 2>/dev/null \\
          && echo "Set unbound workqueue cpumask to \$(printf '0x%x' \$HK_MASK)" \\
          || echo "Failed to set workqueue cpumask"
    fi
fi

# --- Disable kernel timer migration ------------------------------------
# nohz_full already kills the periodic tick on isolated cores, but the
# timer migrator can still cross CPUs and trip IPIs. Setting this to 0
# pins hrtimers to the CPU that armed them.
if [[ -w /proc/sys/kernel/timer_migration ]]; then
    echo 0 > /proc/sys/kernel/timer_migration 2>/dev/null \\
      && echo "Disabled kernel.timer_migration" \\
      || echo "Failed to disable kernel.timer_migration"
fi

# --- Restrict soft/hard-lockup watchdog to housekeeping ----------------
# nohz_full does NOT auto-restrict watchdog_cpumask. Each watched CPU
# spawns a watchdog/N kthread that wakes every watchdog_thresh seconds;
# on an isolated core that's a periodic jitter source. Restricting the
# mask keeps the safety net on housekeeping cores.
if [[ -w /proc/sys/kernel/watchdog_cpumask && -n "\$HK_EXPANDED" ]]; then
    HK_LIST_FOR_WD=\$(echo "\$HK_EXPANDED" | tr ' ' ',' | sed 's/^,//;s/,\$//')
    if echo "\$HK_LIST_FOR_WD" > /proc/sys/kernel/watchdog_cpumask 2>/dev/null; then
        echo "Restricted watchdog_cpumask to housekeeping (\$HK_LIST_FOR_WD)"
    else
        echo "Failed to restrict watchdog_cpumask"
    fi
fi

exit 0
BOOT_EOF

    $SUDO chmod +x "$script_path"

    $SUDO tee "$service_path" > /dev/null <<SERVICE_EOF
[Unit]
Description=EtherCAT IRQ Affinity + NIC Tuning + RT Core Lock
After=network.target
Wants=network.target

[Service]
Type=oneshot
ExecStart=$script_path
RemainAfterExit=yes

[Install]
WantedBy=multi-user.target
SERVICE_EOF

    $SUDO systemctl daemon-reload
    $SUDO systemctl enable "$(basename "$service_path")"
    echo -e "${GREEN}  Wrote $service_path${NC}"
    echo -e "${GREEN}  Wrote $script_path${NC}"
    echo -e "${GREEN}  Enabled $(basename "$service_path")${NC}"
}

remove_ethercat_rt_service() {
    local service_path="${1:-/etc/systemd/system/ethercat-irq-affinity.service}"
    local script_path="${2:-/usr/local/bin/ethercat-irq-affinity.sh}"
    local service_name
    service_name=$(basename "$service_path")

    echo -e "${BLUE}Removing EtherCAT RT service...${NC}"

    if [[ -f "$service_path" ]]; then
        $SUDO systemctl disable "$service_name" 2>/dev/null || true
        $SUDO rm -f "$service_path"
        $SUDO systemctl daemon-reload
        echo -e "${GREEN}  Removed $service_path${NC}"
    fi

    if [[ -f "$script_path" ]]; then
        $SUDO rm -f "$script_path"
        echo -e "${GREEN}  Removed $script_path${NC}"
    fi
}

# ===========================================================================
# cpusets.service — boot-time cpuset partition activation
# ===========================================================================
#
# Installs:
#   - <install_dir>/manage_cpusets.sh     (copy of the tool)
#   - <install_dir>/lib/*.sh              (library copies)
#   - /usr/local/sbin/apply-cpusets       (wrapper)
#   - /etc/cpusets.conf                   (config file)
#   - /etc/systemd/system/cpusets.service (unit)
#
# The installer copies the source tree so the service is self-contained at
# runtime and does not break if the original source tree moves.
#
# Arguments: source_script, config_file,
#            [install_dir=/usr/local/lib/manage_cpusets],
#            [wrapper_path=/usr/local/sbin/apply-cpusets],
#            [etc_config=/etc/cpusets.conf],
#            [service_path=/etc/systemd/system/cpusets.service]
write_cpusets_service() {
    local source_script="$1"
    local config_file="$2"
    local install_dir="${3:-/usr/local/lib/manage_cpusets}"
    local wrapper_path="${4:-/usr/local/sbin/apply-cpusets}"
    local etc_config="${5:-/etc/cpusets.conf}"
    local service_path="${6:-/etc/systemd/system/cpusets.service}"

    local source_dir
    source_dir="$(cd "$(dirname "$source_script")" && pwd)"

    if [[ ! -f "$source_script" ]]; then
        echo -e "${YELLOW}  Source script $source_script not found${NC}" >&2
        return 1
    fi
    if [[ ! -d "$source_dir/lib" ]]; then
        echo -e "${YELLOW}  lib/ directory not found next to $source_script${NC}" >&2
        return 1
    fi
    if [[ ! -f "$config_file" ]]; then
        echo -e "${YELLOW}  Config $config_file not found${NC}" >&2
        return 1
    fi

    echo -e "${BLUE}Installing cpusets service...${NC}"

    $SUDO mkdir -p "$install_dir/lib"
    $SUDO cp "$source_script"       "$install_dir/manage_cpusets.sh"
    $SUDO cp "$source_dir/lib/"*.sh "$install_dir/lib/"
    $SUDO chmod +x "$install_dir/manage_cpusets.sh"

    # Skip the copy when the operator already passed the canonical
    # path; cp would otherwise emit "are the same file" noise. Use
    # -ef to compare inodes (handles symlinks + bind mounts cleanly).
    if [[ ! "$config_file" -ef "$etc_config" ]]; then
        $SUDO cp "$config_file" "$etc_config"
    fi

    $SUDO tee "$wrapper_path" > /dev/null <<WRAPPER_EOF
#!/bin/bash
exec "$install_dir/manage_cpusets.sh" apply "$etc_config" --yes "\$@"
WRAPPER_EOF
    $SUDO chmod +x "$wrapper_path"

    # Ordering: run before docker/user sessions and the k0s kubelet
    # claim CPUs. Phantom-OS local addition: k0scontroller.service /
    # k0sworker.service create the kubepods cgroup covering all CPUs
    # at startup, which blocks partition activation if not ordered
    # after cpusets.service.
    $SUDO tee "$service_path" > /dev/null <<SERVICE_EOF
[Unit]
Description=cpuset partition activation
DefaultDependencies=no
After=local-fs.target
Before=docker.service user@.service multi-user.target systemd-logind.service k0scontroller.service k0sworker.service

[Service]
Type=oneshot
ExecStart=$wrapper_path
ExecStop=$install_dir/manage_cpusets.sh uninstall-runtime
RemainAfterExit=yes

[Install]
WantedBy=multi-user.target
SERVICE_EOF

    $SUDO systemctl daemon-reload
    $SUDO systemctl enable "$(basename "$service_path")"
    echo -e "${GREEN}  Installed $install_dir/manage_cpusets.sh${NC}"
    echo -e "${GREEN}  Installed $install_dir/lib/*.sh${NC}"
    echo -e "${GREEN}  Installed $etc_config${NC}"
    echo -e "${GREEN}  Installed $wrapper_path${NC}"
    echo -e "${GREEN}  Installed $service_path${NC}"
    echo -e "${GREEN}  Enabled $(basename "$service_path")${NC}"
}

remove_cpusets_service() {
    local install_dir="${1:-/usr/local/lib/manage_cpusets}"
    local wrapper_path="${2:-/usr/local/sbin/apply-cpusets}"
    local etc_config="${3:-/etc/cpusets.conf}"
    local service_path="${4:-/etc/systemd/system/cpusets.service}"
    local service_name
    service_name=$(basename "$service_path")

    echo -e "${BLUE}Removing cpusets service...${NC}"

    if [[ -f "$service_path" ]]; then
        $SUDO systemctl disable "$service_name" 2>/dev/null || true
        $SUDO rm -f "$service_path"
        $SUDO systemctl daemon-reload
        echo -e "${GREEN}  Removed $service_path${NC}"
    fi

    if [[ -f "$wrapper_path" ]]; then
        $SUDO rm -f "$wrapper_path"
        echo -e "${GREEN}  Removed $wrapper_path${NC}"
    fi

    if [[ -f "$etc_config" ]]; then
        $SUDO rm -f "$etc_config"
        echo -e "${GREEN}  Removed $etc_config${NC}"
    fi

    if [[ -d "$install_dir" ]]; then
        $SUDO rm -rf "$install_dir"
        echo -e "${GREEN}  Removed $install_dir${NC}"
    fi
}

# ===========================================================================
# /etc/systemd/system.conf.d/cpuaffinity.conf — default CPUAffinity
# ===========================================================================
# Arguments: housekeeping_range, [drop_in_path]
write_affinity_drop_in() {
    local housekeeping="$1"
    local drop_in_path="${2:-/etc/systemd/system.conf.d/cpuaffinity.conf}"

    if [[ -z "$housekeeping" ]]; then
        echo -e "${YELLOW}  housekeeping range empty — refusing to write affinity drop-in${NC}" >&2
        return 1
    fi

    local drop_in_dir
    drop_in_dir=$(dirname "$drop_in_path")

    echo -e "${BLUE}Writing systemd default CPUAffinity drop-in...${NC}"

    $SUDO mkdir -p "$drop_in_dir"
    $SUDO tee "$drop_in_path" > /dev/null <<DROPIN_EOF
# Auto-generated by manage_cpusets.sh
# Restricts default CPU affinity for systemd-spawned services to
# housekeeping cores. Services that legitimately need isolated cores
# must override this via their own CPUAffinity= or AllowedCPUs=.
[Manager]
CPUAffinity=$housekeeping
DROPIN_EOF

    echo -e "${GREEN}  Wrote $drop_in_path (CPUAffinity=$housekeeping)${NC}"
    echo -e "${YELLOW}  Reload with: sudo systemctl daemon-reexec${NC}"
    echo -e "${YELLOW}  Already-running services keep their old affinity until restarted.${NC}"
}

remove_affinity_drop_in() {
    local drop_in_path="${1:-/etc/systemd/system.conf.d/cpuaffinity.conf}"

    if [[ -f "$drop_in_path" ]]; then
        $SUDO rm -f "$drop_in_path"
        echo -e "${GREEN}  Removed $drop_in_path${NC}"
        echo -e "${YELLOW}  Reload with: sudo systemctl daemon-reexec${NC}"
    else
        echo -e "${YELLOW}  No drop-in at $drop_in_path${NC}"
    fi
}
