#!/usr/bin/env bash
# cpusets.sh — bootstrap-side helper around scripts/cpusets/manage_cpusets.sh.
#
# Sourced by scripts/bootstrap-robot.sh. Reads the cpuIsolation: block
# from /etc/phantomos/host-config.yaml, renders /etc/cpusets.conf, and
# drives the vendored manage_cpusets.sh through its non-interactive
# subcommands (apply, install-service, install-affinity-defaults,
# ethercat-rt --rt-core, migrate-cmdline --yes).
#
# Required globals before sourcing:
#   REPO_ROOT  absolute path to the Phantom-OS-KubernetesOptions repo
# Optional:
#   CPUSETS_CONF       /etc/cpusets.conf override
#   CPUSETS_SCRIPT     scripts/cpusets/manage_cpusets.sh override
#
# Logging: relies on caller-provided pass/fail/info/note/skip helpers.

CPUSETS_CONF="${CPUSETS_CONF:-/etc/cpusets.conf}"
CPUSETS_SCRIPT="${CPUSETS_SCRIPT:-$REPO_ROOT/scripts/cpusets/manage_cpusets.sh}"
PIN_KUBEPODS_SCRIPT="${PIN_KUBEPODS_SCRIPT:-$REPO_ROOT/scripts/cpusets/pin-kubepods.sh}"
CPU_ISOLATION_REBOOT_MARKER="${CPU_ISOLATION_REBOOT_MARKER:-/etc/phantomos/cpu-isolation.reboot-pending}"

# Render /etc/cpusets.conf from a JSON cpuIsolation block. Atomic write
# via tmp + mv. The format matches manage_cpusets.sh apply:
#
#   [name]
#   cpus = <range>
#   description = <text>
#
# Args:
#   $1  JSON blob (output of `host-config.py ... get-cpu-isolation-json`)
# Echoes the rendered file path on success.
cpusets_render_conf() {
  local json="$1"
  local dst="$CPUSETS_CONF"
  local tmp
  tmp="$(mktemp)" || return 1

  python3 - "$json" "$tmp" <<'PY' || { rm -f "$tmp"; return 1; }
import json, sys, datetime
data = json.loads(sys.argv[1] or "{}")
out = sys.argv[2]
parts = data.get("partitions") or []
now_iso = datetime.datetime.now(datetime.timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
with open(out, "w") as f:
    f.write(f"# Generated by bootstrap-robot.sh on {now_iso}\n")
    f.write("# Source: /etc/phantomos/host-config.yaml cpuIsolation:\n")
    f.write("# Re-run bootstrap-robot.sh after editing host-config.yaml.\n\n")
    for p in parts:
        f.write(f"[{p['name']}]\n")
        f.write(f"cpus = {p['cpus']}\n")
        if p.get("description"):
            f.write(f"description = {p['description']}\n")
        f.write("\n")
PY

  mkdir -p "$(dirname "$dst")"
  if ! mv "$tmp" "$dst"; then
    rm -f "$tmp"
    return 1
  fi
  chmod 0644 "$dst"
  printf '%s\n' "$dst"
}

# Wrap the vendored script so callers don't have to remember the path.
# Forwards stdout/stderr; exit code propagates.
cpusets_run() {
  "$CPUSETS_SCRIPT" "$@"
}

# Read a top-level field from the cpuIsolation JSON.
# Args:
#   $1  json
#   $2  field name
# Echoes the value (may be empty), exit code is always 0 — callers
# decide what an empty value means.
cpusets_json_field() {
  python3 - "$1" "$2" <<'PY' 2>/dev/null || true
import json, sys
data = json.loads(sys.argv[1] or "{}")
v = data.get(sys.argv[2])
if v is None or v is False:
    pass
elif v is True:
    print("true")
else:
    print(v)
PY
}

# Read nic.iface and nic.irqCore — empty when absent. The legacy
# nic.rtCore key is auto-translated to irqCore for back-compat.
cpusets_json_nic() {
  python3 - "$1" <<'PY' 2>/dev/null || true
import json, sys
data = json.loads(sys.argv[1] or "{}")
nic = data.get("nic") or {}
iface = nic.get("iface", "")
irq = nic.get("irqCore")
if irq is None:
    irq = nic.get("rtCore", "")
print(iface)
print(irq if irq != "" else "")
PY
}

# Read top-level cpuIsolation.dmaRtCpu (the SOEM RT loop core).
# Returns empty string when not set — caller decides whether to fall
# back to nic.irqCore for legacy configs.
cpusets_json_dma_rt_cpu() {
  python3 - "$1" <<'PY' 2>/dev/null || true
import json, sys
data = json.loads(sys.argv[1] or "{}")
v = data.get("dmaRtCpu", "")
print(v if v != "" else "")
PY
}

# Names of declared partitions, one per line.
cpusets_json_partition_names() {
  python3 - "$1" <<'PY' 2>/dev/null || true
import json, sys
data = json.loads(sys.argv[1] or "{}")
for p in (data.get("partitions") or []):
    print(p.get("name", ""))
PY
}

# Render a service drop-in that places the unit in the named RT slice
# and clears any manager-wide CPUAffinity= (which would otherwise narrow
# the process's sched_setaffinity to housekeeping cores and conflict
# with the slice's AllowedCPUs).
#
# Args:
#   $1  service unit basename (e.g. dma-ethercat.service)
#   $2  slice name (without .slice suffix; e.g. ecat1)
# Echoes the rendered path on success.
cpusets_render_service_slice_dropin() {
  local unit="$1" slice="$2"
  if [ -z "$unit" ] || [ -z "$slice" ]; then
    return 1
  fi
  local dir="/etc/systemd/system/${unit}.d"
  local dst="${dir}/10-slice.conf"
  local tmp
  tmp="$(mktemp)" || return 1
  cat > "$tmp" <<EOF
# Auto-generated by bootstrap-robot.sh
# Source: /etc/phantomos/host-config.yaml cpuIsolation
#
# Place ${unit} in the ${slice}.slice RT cgroup so it can run on the
# isolated cpus. Clearing CPUAffinity= overrides the manager-wide drop-in
# at /etc/systemd/system.conf.d/cpuaffinity.conf so the process's
# sched_setaffinity isn't pre-narrowed to housekeeping.
[Service]
CPUAffinity=
Slice=${slice}.slice
EOF
  mkdir -p "$dir"
  if ! mv "$tmp" "$dst"; then
    rm -f "$tmp"
    return 1
  fi
  chmod 0644 "$dst"
  printf '%s\n' "$dst"
}
