apiVersion: apps/v1
kind: Deployment
metadata:
  name: operator-ui
  namespace: argus
spec:
  template:
    spec:
      containers:
        - name: operator-ui
          env:
            - name: AI_PC_URL
              value: http://100.124.202.97:5000
