set -e
REPO=/root/foundation/DMA/Phantom-OS-KubernetesOptions

# ============================================================
# 1. Suspend ArgoCD self-heal so it doesn't fight us mid-recovery
# ============================================================
k0s kubectl -n argocd patch application phantomos-mk09 --type=merge \
  -p='{"spec":{"syncPolicy":{"automated":{"selfHeal":false,"prune":false}}}}'

# ============================================================
# 2. Scale every stateful consumer to 0
# ============================================================
k0s kubectl -n argus      scale statefulset mongodb  --replicas=0
k0s kubectl -n argus      scale statefulset redis    --replicas=0
k0s kubectl -n nimbus     scale statefulset postgres --replicas=0
k0s kubectl -n nimbus     scale deploy eg-server     --replicas=0
k0s kubectl -n nimbus     scale deploy eg-jobs       --replicas=0
k0s kubectl -n registry   scale deploy k0s-registry  --replicas=0

# Wait for pods to terminate
sleep 15
k0s kubectl get pod -A -l 'app in (mongodb,redis,postgres,k0s-registry,eg-server,eg-jobs)' \
  --no-headers 2>/dev/null | head

# ============================================================
# 3. Delete all the PVCs in scope (PV-protection finalizer
#    releases as soon as the consumers above are gone)
# ============================================================
k0s kubectl -n argus      delete pvc data-mongodb-0 data-redis-0 --wait=true
k0s kubectl -n nimbus     delete pvc data-postgres-0 recordings-pvc --wait=true
k0s kubectl -n registry   delete pvc k0s-registry-pvc --wait=true

# ============================================================
# 4. Delete all PVs (Retain reclaim → hostPath data preserved)
# ============================================================
k0s kubectl delete pv mongodb-pv redis-pv postgres-pv recordings-pv k0s-registry-pv

# Sanity check: the on-disk data is still there
sudo ls /var/lib/k0s-data/mongodb /var/lib/k0s-data/redis /var/lib/k0s-data/postgres /root/recordings /var/lib/registry 2>/dev/null

# ============================================================
# 5. Reapply manifests — recreates PVs (with correct claimRef),
#    PVCs (recordings-pvc + k0s-registry-pvc; the others are
#    auto-generated by their StatefulSets), and the rest of the stack
# ============================================================
k0s kubectl apply -k $REPO/manifests/robots/mk09/

# Confirm fresh PVs have correct claimRef
k0s kubectl get pv -o jsonpath='{range .items[*]}{.metadata.name}: claimRef={.spec.claimRef.namespace}/{.spec.claimRef.name} status={.status.phase}{"\n"}{end}'

# Expect each line to look like: <pv-name>: claimRef=<ns>/<correct-pvc> status=Available

# ============================================================
# 6. Scale stateful services back up — IN ORDER. Registry first so
#    its PVC claims k0s-registry-pv before any race window opens.
# ============================================================
k0s kubectl -n registry  scale deploy k0s-registry  --replicas=1
k0s kubectl -n registry  rollout status deploy/k0s-registry  --timeout=180s

k0s kubectl -n argus     scale statefulset mongodb  --replicas=1
k0s kubectl -n argus     scale statefulset redis    --replicas=1
k0s kubectl -n nimbus    scale statefulset postgres --replicas=1
k0s kubectl -n argus     rollout status statefulset/mongodb  --timeout=180s
k0s kubectl -n argus     rollout status statefulset/redis    --timeout=180s
k0s kubectl -n nimbus    rollout status statefulset/postgres --timeout=180s

k0s kubectl -n nimbus    scale deploy eg-server --replicas=1
k0s kubectl -n nimbus    scale deploy eg-jobs   --replicas=1
k0s kubectl -n nimbus    rollout status deploy/eg-server --timeout=180s
k0s kubectl -n nimbus    rollout status deploy/eg-jobs   --timeout=180s

# ============================================================
# 7. Re-enable ArgoCD self-heal + prune
# ============================================================
k0s kubectl -n argocd patch application phantomos-mk09 --type=merge \
  -p='{"spec":{"syncPolicy":{"automated":{"selfHeal":true,"prune":true}}}}'
k0s kubectl -n argocd annotate application phantomos-mk09 \
  argocd.argoproj.io/refresh=hard --overwrite

# ============================================================
# 8. Verify everything's back
# ============================================================
echo "=== PVs ==="
k0s kubectl get pv -o wide

echo "=== PVCs (all stateful) ==="
k0s kubectl -n argus    get pvc
k0s kubectl -n nimbus   get pvc
k0s kubectl -n registry get pvc

echo "=== Stateful pods ==="
k0s kubectl -n argus    get pod
k0s kubectl -n nimbus   get pod
k0s kubectl -n registry get pod

echo "=== Registry catalog (should show pre-existing images) ==="
curl -fs http://localhost:5443/v2/_catalog

echo "=== ArgoCD status ==="
k0s kubectl -n argocd get application phantomos-mk09 \
  -o jsonpath='Sync: {.status.sync.status}{"\n"}Health: {.status.health.status}{"\n"}'

