apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - mongodb.yaml
  - redis.yaml
  - argus-auth.yaml
  - argus-user.yaml
  - argus-company.yaml
  - argus-gateway.yaml
  - operator-ui.yaml
  - nginx.yaml
